data:
  train_path: data/raw/train_solo_track.parquet
  test_path: data/raw/test_solo_track.parquet
  submission_dir: data/submissions
  submission_name: submission_ridge_final.csv

model:
  type: ridge
  alpha: 4.0
  train_window_days: 5
  step_minutes: 30
  forecast_horizon: 8

features:
  selected_features:
    - route_id
    - status_1
    - status_2
    - status_3
    - status_4
    - status_5
    - status_6
    - target_now
    - target_lag_1
    - target_lag_2
    - target_lag_4
    - target_lag_8
    - target_lag_48
    - target_lag_336
    - target_roll_mean_4
    - target_roll_std_4
    - target_roll_mean_8
    - target_roll_std_8
    - target_roll_mean_48
    - target_roll_std_48
    - status_1_lag_1
    - status_1_lag_2
    - status_1_lag_4
    - status_1_lag_8
    - status_1_lag_48
    - status_2_lag_1
    - status_2_lag_2
    - status_2_lag_4
    - status_2_lag_8
    - status_2_lag_48
    - status_3_lag_1
    - status_3_lag_2
    - status_3_lag_4
    - status_3_lag_8
    - status_3_lag_48
    - status_4_lag_1
    - status_4_lag_2
    - status_4_lag_4
    - status_4_lag_8
    - status_4_lag_48
    - status_5_lag_1
    - status_5_lag_2
    - status_5_lag_4
    - status_5_lag_8
    - status_5_lag_48
    - status_6_lag_1
    - status_6_lag_2
    - status_6_lag_4
    - status_6_lag_8
    - status_6_lag_48
    - status_1_roll_mean_4
    - status_1_roll_mean_8
    - status_1_roll_mean_48
    - status_2_roll_mean_4
    - status_2_roll_mean_8
    - status_2_roll_mean_48
    - status_3_roll_mean_4
    - status_3_roll_mean_8
    - status_3_roll_mean_48
    - status_4_roll_mean_4
    - status_4_roll_mean_8
    - status_4_roll_mean_48
    - status_5_roll_mean_4
    - status_5_roll_mean_8
    - status_5_roll_mean_48
    - status_6_roll_mean_4
    - status_6_roll_mean_8
    - status_6_roll_mean_48
    - status_1_roll_std_4
    - status_1_roll_std_8
    - status_1_roll_std_48
    - status_2_roll_std_4
    - status_2_roll_std_8
    - status_2_roll_std_48
    - status_3_roll_std_4
    - status_3_roll_std_8
    - status_3_roll_std_48
    - status_4_roll_std_4
    - status_4_roll_std_8
    - status_4_roll_std_48
    - status_5_roll_std_4
    - status_5_roll_std_8
    - status_5_roll_std_48
    - status_6_roll_std_4
    - status_6_roll_std_8
    - status_6_roll_std_48

calibration:
  type: global_scale
  global_scale: 0.9975